version: '3'
services:
  broker-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro/broker-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro/broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro/authentication-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro/authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "9091:9091"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro/logger-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro/logger-service/logger-service.dockerfile
    restart: always
    ports:
      - "9092:9092"
    deploy:
      mode: replicated
      replicas: 1

  mailer-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro/mail-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro/mail-service/mailer-service.dockerfile
    restart: always
    ports:
      - "9093:9093"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: john.smith@example.com

  listener-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro/listener-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro/listener-service/listener-service.dockerfile
    restart: always
    ports:
      - "9094:9094"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
        - go-micro:/var/lib/postgresql/data/


  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - go-micro:/data/db

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - go-micro:/var/lib/rabbitmq/

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  go-micro:
    external: true